#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : renderdoc
Version  : 1.5.reduced
Release  : 13
URL      : http://localhost/cgit/projects/renderdoc/snapshot/renderdoc-1.5-reduced.tar.xz
Source0  : http://localhost/cgit/projects/renderdoc/snapshot/renderdoc-1.5-reduced.tar.xz
Source1  : https://github.com/baldurk/swig/archive/renderdoc-modified-7.tar.gz
Summary  : Allows param links in Sphinx function/method descriptions to be linkable
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSD-3-Clause-Clear BSL-1.0 GPL-2.0 GPL-3.0 HPND MIT Zlib
Requires: renderdoc-bin = %{version}-%{release}
Requires: renderdoc-data = %{version}-%{release}
Requires: renderdoc-lib = %{version}-%{release}
Requires: renderdoc-license = %{version}-%{release}
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : glibc-dev
BuildRequires : glslang-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : lz4-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5X11Extras)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(vulkan)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-keysyms)
BuildRequires : pugixml-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : zstd-dev
Patch1: 0001-Don-t-use-bundled-sources-for-components-we-have-in-.patch

%description
Sphinx Paramlinks
        ==================

%package bin
Summary: bin components for the renderdoc package.
Group: Binaries
Requires: renderdoc-data = %{version}-%{release}
Requires: renderdoc-license = %{version}-%{release}

%description bin
bin components for the renderdoc package.


%package data
Summary: data components for the renderdoc package.
Group: Data

%description data
data components for the renderdoc package.


%package dev
Summary: dev components for the renderdoc package.
Group: Development
Requires: renderdoc-lib = %{version}-%{release}
Requires: renderdoc-bin = %{version}-%{release}
Requires: renderdoc-data = %{version}-%{release}
Provides: renderdoc-devel = %{version}-%{release}
Requires: renderdoc = %{version}-%{release}

%description dev
dev components for the renderdoc package.


%package doc
Summary: doc components for the renderdoc package.
Group: Documentation

%description doc
doc components for the renderdoc package.


%package lib
Summary: lib components for the renderdoc package.
Group: Libraries
Requires: renderdoc-data = %{version}-%{release}
Requires: renderdoc-license = %{version}-%{release}

%description lib
lib components for the renderdoc package.


%package license
Summary: license components for the renderdoc package.
Group: Default

%description license
license components for the renderdoc package.


%prep
%setup -q -n renderdoc-1.5-reduced
cd %{_builddir}
tar xf %{_sourcedir}/renderdoc-modified-7.tar.gz
cd %{_builddir}/renderdoc-1.5-reduced
mkdir -p ../swig
cp -r %{_builddir}/swig-renderdoc-modified-7/* %{_builddir}/renderdoc-1.5-reduced/../swig
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576110193
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_VERSION_STABLE=ON \
-DBUILD_VERSION_DIST_NAME="clear" \
-DENABLE_GL=ON \
-DENABLE_QRENDERDOC=ON \
-DENABLE_VULKAN=ON \
-DENABLE_VULKAN=ENABLE_RENDERDOCCMD \
-DRENDERDOC_SWIG_PACKAGE=%{SOURCE1} \
-DLIB_SUBFOLDER=renderdoc \
-DVULKAN_LAYER_FOLDER=/usr/share/vulkan/implicit_layer.d
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1576110193
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/renderdoc
cp %{_builddir}/renderdoc-1.5-reduced/LICENSE.md %{buildroot}/usr/share/package-licenses/renderdoc/96f99428f9168e7cf7a806e2e5f4e70ea89a2533
cp %{_builddir}/renderdoc-1.5-reduced/docs/sphinx_exts/sphinx_paramlinks/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/66478105583dc4e96fec98299f68397e4a9c6927
cp %{_builddir}/renderdoc-1.5-reduced/qrenderdoc/3rdparty/scintilla/License.txt %{buildroot}/usr/share/package-licenses/renderdoc/9da27f7b263edb706105ccd68880474013b11bca
cp %{_builddir}/renderdoc-1.5-reduced/qrenderdoc/3rdparty/toolwindowmanager/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/57570fcce4be9b86d56e300cb08c92e39b516ca9
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/3rdparty/breakpad/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/86dabb511ec367808a04ba4b87c4a3e0b97765e2
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/3rdparty/catch/LICENSE.txt %{buildroot}/usr/share/package-licenses/renderdoc/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/3rdparty/glslang/LICENSE.txt %{buildroot}/usr/share/package-licenses/renderdoc/b6162cb1ae79b7e8c672797b496ecd4575874592
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/3rdparty/include-bin/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/d84cd641b9edb0f1071324bebce41507c6ef29a6
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/3rdparty/interceptor-lib/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/78f5cba7977d1ead96f94a5efd38de0a3dba25a6
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/3rdparty/pugixml/LICENSE.md %{buildroot}/usr/share/package-licenses/renderdoc/1194197740cc9b4f68f18f8f5d7e2f46693582da
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/3rdparty/zstd/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/c4130945ca3d1f8ea4a3e8af36d3c18b2232116c
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/driver/ihv/amd/official/GPUPerfAPI/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/94ea9b1c36be0c127f619add95cfd1e62869d401
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/driver/ihv/amd/official/RGA/Common/License.txt %{buildroot}/usr/share/package-licenses/renderdoc/c9cf0423322b3bc3403dc546ee34b45f330755e9
cp %{_builddir}/renderdoc-1.5-reduced/renderdoc/driver/ihv/amd/official/RGA/elf/LICENSE.md %{buildroot}/usr/share/package-licenses/renderdoc/96e3d1ffcb5a4a6715839da6b5add6fd69367956
cp %{_builddir}/renderdoc-1.5-reduced/util/installer/LICENSE.rtf %{buildroot}/usr/share/package-licenses/renderdoc/9e60dae05623b7fc531fd8c4214636f84ded2520
cp %{_builddir}/swig/CCache/COPYING %{buildroot}/usr/share/package-licenses/renderdoc/075d599585584bb0e4b526f5c40cb6b17e0da35a
cp %{_builddir}/swig/LICENSE-GPL %{buildroot}/usr/share/package-licenses/renderdoc/8624bcdae55baeef00cd11d5dfcfa60f68710a02
pushd clr-build
%make_install
popd
## install_append content
rm -rf /usr/share/menu/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qrenderdoc
/usr/bin/renderdoccmd

%files data
%defattr(-,root,root,-)
/usr/share/applications/renderdoc.desktop
/usr/share/icons/hicolor/scalable/mimetypes/application-x-renderdoc-capture.svg
/usr/share/menu/renderdoc
/usr/share/mime-packages/renderdoc-capture.xml
/usr/share/pixmaps/renderdoc-icon-16x16.xpm
/usr/share/pixmaps/renderdoc-icon-32x32.xpm
/usr/share/thumbnailers/renderdoc.thumbnailer
/usr/share/vulkan/implicit_layer.d/renderdoc_capture.json

%files dev
%defattr(-,root,root,-)
/usr/include/renderdoc.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/renderdoc/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/renderdoc/librenderdoc.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/renderdoc/075d599585584bb0e4b526f5c40cb6b17e0da35a
/usr/share/package-licenses/renderdoc/1194197740cc9b4f68f18f8f5d7e2f46693582da
/usr/share/package-licenses/renderdoc/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/renderdoc/57570fcce4be9b86d56e300cb08c92e39b516ca9
/usr/share/package-licenses/renderdoc/66478105583dc4e96fec98299f68397e4a9c6927
/usr/share/package-licenses/renderdoc/78f5cba7977d1ead96f94a5efd38de0a3dba25a6
/usr/share/package-licenses/renderdoc/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/renderdoc/86dabb511ec367808a04ba4b87c4a3e0b97765e2
/usr/share/package-licenses/renderdoc/94ea9b1c36be0c127f619add95cfd1e62869d401
/usr/share/package-licenses/renderdoc/96e3d1ffcb5a4a6715839da6b5add6fd69367956
/usr/share/package-licenses/renderdoc/96f99428f9168e7cf7a806e2e5f4e70ea89a2533
/usr/share/package-licenses/renderdoc/9da27f7b263edb706105ccd68880474013b11bca
/usr/share/package-licenses/renderdoc/9e60dae05623b7fc531fd8c4214636f84ded2520
/usr/share/package-licenses/renderdoc/b6162cb1ae79b7e8c672797b496ecd4575874592
/usr/share/package-licenses/renderdoc/c4130945ca3d1f8ea4a3e8af36d3c18b2232116c
/usr/share/package-licenses/renderdoc/c9cf0423322b3bc3403dc546ee34b45f330755e9
/usr/share/package-licenses/renderdoc/d84cd641b9edb0f1071324bebce41507c6ef29a6
