#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : renderdoc
Version  : 1.4.reduced
Release  : 8
URL      : http://localhost/cgit/projects/renderdoc/snapshot/renderdoc-1.4-reduced.tar.xz
Source0  : http://localhost/cgit/projects/renderdoc/snapshot/renderdoc-1.4-reduced.tar.xz
Source1  : https://github.com/baldurk/swig/archive/renderdoc-modified-6.tar.gz
Summary  : Allows param links in Sphinx function/method descriptions to be linkable
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSD-3-Clause-Clear BSL-1.0 HPND MIT Zlib
Requires: renderdoc-bin = %{version}-%{release}
Requires: renderdoc-data = %{version}-%{release}
Requires: renderdoc-lib = %{version}-%{release}
Requires: renderdoc-license = %{version}-%{release}
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : glibc-dev
BuildRequires : glslang-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : lz4-dev
BuildRequires : openjdk11
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5X11Extras)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(vulkan)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-keysyms)
BuildRequires : pugixml-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : zstd-dev
Patch1: 0001-Don-t-use-bundled-sources-for-components-we-have-in-.patch

%description
Sphinx Paramlinks
        ==================

%package bin
Summary: bin components for the renderdoc package.
Group: Binaries
Requires: renderdoc-data = %{version}-%{release}
Requires: renderdoc-license = %{version}-%{release}

%description bin
bin components for the renderdoc package.


%package data
Summary: data components for the renderdoc package.
Group: Data

%description data
data components for the renderdoc package.


%package dev
Summary: dev components for the renderdoc package.
Group: Development
Requires: renderdoc-lib = %{version}-%{release}
Requires: renderdoc-bin = %{version}-%{release}
Requires: renderdoc-data = %{version}-%{release}
Provides: renderdoc-devel = %{version}-%{release}
Requires: renderdoc = %{version}-%{release}

%description dev
dev components for the renderdoc package.


%package doc
Summary: doc components for the renderdoc package.
Group: Documentation

%description doc
doc components for the renderdoc package.


%package lib
Summary: lib components for the renderdoc package.
Group: Libraries
Requires: renderdoc-data = %{version}-%{release}
Requires: renderdoc-license = %{version}-%{release}

%description lib
lib components for the renderdoc package.


%package license
Summary: license components for the renderdoc package.
Group: Default

%description license
license components for the renderdoc package.


%prep
%setup -q -n renderdoc-1.4-reduced
cd ..
%setup -q -T -D -n renderdoc-1.4-reduced -b 1
mkdir -p ../swig
cp -r %{_topdir}/BUILD/swig-renderdoc-modified-6/* %{_topdir}/BUILD/renderdoc-1.4-reduced/../swig
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564692461
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_VERSION_STABLE=ON \
-DBUILD_VERSION_DIST_NAME="clear" \
-DENABLE_GL=ON \
-DENABLE_QRENDERDOC=ON \
-DENABLE_VULKAN=ON \
-DENABLE_VULKAN=ENABLE_RENDERDOCCMD \
-DRENDERDOC_SWIG_PACKAGE=%{SOURCE1} \
-DLIB_SUBFOLDER=renderdoc \
-DVULKAN_LAYER_FOLDER=/usr/share/vulkan/implicit_layer.d
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1564692461
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/renderdoc
cp LICENSE.md %{buildroot}/usr/share/package-licenses/renderdoc/LICENSE.md
cp docs/sphinx_exts/sphinx_paramlinks/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/docs_sphinx_exts_sphinx_paramlinks_LICENSE
cp qrenderdoc/3rdparty/scintilla/License.txt %{buildroot}/usr/share/package-licenses/renderdoc/qrenderdoc_3rdparty_scintilla_License.txt
cp qrenderdoc/3rdparty/toolwindowmanager/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/qrenderdoc_3rdparty_toolwindowmanager_LICENSE
cp renderdoc/3rdparty/breakpad/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_breakpad_LICENSE
cp renderdoc/3rdparty/catch/LICENSE.txt %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_catch_LICENSE.txt
cp renderdoc/3rdparty/glslang/LICENSE.txt %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_glslang_LICENSE.txt
cp renderdoc/3rdparty/include-bin/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_include-bin_LICENSE
cp renderdoc/3rdparty/interceptor-lib/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_interceptor-lib_LICENSE
cp renderdoc/3rdparty/pugixml/LICENSE.md %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_pugixml_LICENSE.md
cp renderdoc/3rdparty/zstd/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_zstd_LICENSE
cp renderdoc/driver/ihv/amd/official/GPUPerfAPI/LICENSE %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_driver_ihv_amd_official_GPUPerfAPI_LICENSE
cp renderdoc/driver/ihv/amd/official/RGA/Common/License.txt %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_driver_ihv_amd_official_RGA_Common_License.txt
cp renderdoc/driver/ihv/amd/official/RGA/elf/LICENSE.md %{buildroot}/usr/share/package-licenses/renderdoc/renderdoc_driver_ihv_amd_official_RGA_elf_LICENSE.md
pushd clr-build
%make_install
popd
## install_append content
rm -rf /usr/share/menu/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qrenderdoc
/usr/bin/renderdoccmd

%files data
%defattr(-,root,root,-)
/usr/share/applications/renderdoc.desktop
/usr/share/icons/hicolor/scalable/mimetypes/application-x-renderdoc-capture.svg
/usr/share/menu/renderdoc
/usr/share/mime-packages/renderdoc-capture.xml
/usr/share/pixmaps/renderdoc-icon-16x16.xpm
/usr/share/pixmaps/renderdoc-icon-32x32.xpm
/usr/share/thumbnailers/renderdoc.thumbnailer
/usr/share/vulkan/implicit_layer.d/renderdoc_capture.json

%files dev
%defattr(-,root,root,-)
/usr/include/*.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/renderdoc/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/renderdoc/librenderdoc.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/renderdoc/LICENSE.md
/usr/share/package-licenses/renderdoc/docs_sphinx_exts_sphinx_paramlinks_LICENSE
/usr/share/package-licenses/renderdoc/qrenderdoc_3rdparty_scintilla_License.txt
/usr/share/package-licenses/renderdoc/qrenderdoc_3rdparty_toolwindowmanager_LICENSE
/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_breakpad_LICENSE
/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_catch_LICENSE.txt
/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_glslang_LICENSE.txt
/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_include-bin_LICENSE
/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_interceptor-lib_LICENSE
/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_pugixml_LICENSE.md
/usr/share/package-licenses/renderdoc/renderdoc_3rdparty_zstd_LICENSE
/usr/share/package-licenses/renderdoc/renderdoc_driver_ihv_amd_official_GPUPerfAPI_LICENSE
/usr/share/package-licenses/renderdoc/renderdoc_driver_ihv_amd_official_RGA_Common_License.txt
/usr/share/package-licenses/renderdoc/renderdoc_driver_ihv_amd_official_RGA_elf_LICENSE.md
